title: Craft a pull switch
hero_image: images/banner.png
description: How to craft a pull switch for a Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - 
    title: Craft a pull switch
