
title: Fabriquer un interrupteur à tirette
hero_image: images/banner.png
description: Comment fabriquer un interrupteur à tirette pour un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Fabriquer un interrupteur à tirette
